# Generated by Django 4.1.4 on 2022-12-31 23:29

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('numberplate', models.CharField(default='00-AA-AA', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), cars.models.max_value_current_year])),
                ('fuel', models.CharField(max_length=100)),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['numberplate'],
            },
        ),
    ]
