# Generated by Django 4.1.4 on 2022-12-31 23:51

import cars.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_purchase_date_car_sales_date_alter_car_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1960), cars.models.max_value_current_year]),
        ),
        migrations.CreateModel(
            name='MaintenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_change', models.PositiveIntegerField()),
                ('distribution_set', models.PositiveIntegerField()),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car')),
            ],
            options={
                'verbose_name_plural': 'Maintence Data',
            },
        ),
    ]
