# Generated by Django 4.1.4 on 2023-01-01 16:19

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_distribution_set_maintencedata_distribution_set_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sales_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1960), cars.models.max_value_current_year]),
        ),
    ]
