# Generated by Django 4.1.4 on 2023-01-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_sales_date_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
